#SOME TODOS OS NUMEROS DE 1 A 100 UTILIZANDO FOR


#ENCONTRE A QUANTIDADE DE VOGAIS NUMA STRING QUE O USUARIO DIGITOU

print('EXERCICIO 1')
soma = 0
for i in range(1,101):
    soma += i
    print(soma)